version: '3.8'

services:
  extension-build:
    build:
      context: .
      dockerfile: Dockerfile
    image: extension-build
    volumes:
      - .:/extension
    working_dir: /extension
    entrypoint: /extension/scripts/build.sh
