
#define MAXPLAYERS 65

#define INDEX_LOWER 0
#define INDEX_LOW 1
#define INDEX_HIGH 2
#define INDEX_HIGHER 3

#define LEVEL_LOWER -2500
#define LEVEL_LOW -1000
#define LEVEL_HIGH 1000
#define LEVEL_HIGHER 2500
#define MAX_LEVELS 4

#define MAX_FRAMEBUFFER_SAMPLES 480
#define STEAM_HEADER_SIZE 12
#define CRC_SIZE 4
#define CHANNELS 1
#define APPLICATION OPUS_APPLICATION_AUDIO
#define BITRATE 32000
#define MAX_FRAME_SIZE 6 * 960
#define MAX_PACKET_SIZE 4096